version: '3'
services:
  mongo-client:
    image: mongo:latest
    container_name: mongo-client
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      command: mongod --auth
  branchesapp-main:
    image: branches:v1
    depends_on:
      - mongo-client
    container_name: branchesapp-main
    environment:
      - SERVER_PORT=9010
    ports:
      - 9010:9010
    build: .
  branchesapp-secondary:
    image: branches:v1
    depends_on:
      - mongo-client
    container_name: branchesapp-secondary
    environment:
      - SERVER_PORT=9020
    ports:
      - 9020:9020
    build: .